### ISSUE TITLE
Can't open Email app.

### ISSUE THREAD

**Issue by Artlighter** [henkaku/offline-installer#1]
After reboot PS Vita system I can't open Email app. Have a message like - "Install new firmware to open Email..."

**Comment by xyzz** [comment]
Try deleting ux0:email from molecularShell, then open and close Email app, then open offlineInstaller and install again.

**Comment by Artlighter** [comment]
Ok, "ux0:email" was deleted. After I tried reopen Email app, but system required install new firm. again and not opened app. After runing Offlineinstaller i saw message: "It seems that the mail database does not exist..."

**Comment by xyzz** [comment]
Can you post a photo or a screenshot of the error message (in English)?

**Comment by Artlighter** [comment]
http://imgur.com/a/LWYjA

**Comment by xyzz** [comment]
I meant the email app error, not offlineInstaller error.

**Comment by Artlighter** [comment]
http://imgur.com/a/7YUD1

message from Email app in offline mode

p.s. 
when mode of Vita is online - email app still requesting update

**Comment by ghost** [comment]
@Artlighter Can you  upload to imgur please? I dont think anyone can help you with all those ads blocking your photo

**Comment by Artlighter** [comment]
links on images was updated

**Comment by ghost** [comment]
Why dont you try turning on the Wi-Fi on your vita and using [Vita Update Blocker](http://wololo.net/talk/viewtopic.php?f=116&t=46427)  ? It might stop you from getting that update prompt. It might not though.

**Comment by xyzz** [comment]
Can you upload a screenshot of online mode? I've never seen email app ask for update.

**Comment by Artlighter** [comment]
@xyzz http://imgur.com/a/vwibH =>
when I put Cancel =>
http://imgur.com/a/V2YVT

@SpooneyH20  Blocker doesn't work

**Comment by ghost** [comment]
@Artlighter Did the blocker app on your computer not work? Or did it not block the update prompt?

**Comment by Artlighter** [comment]
Ok, guys. my fault, I was careless, all working perfect. I restored my system from backup. Blocker and Offlineinstaller are pretty exelent show yourself. Reason of the trouble - I removed wrong files... Thank you for your time. My apologies ^^
p.s. Advice for guys like me - Be attend! Read all info thoroughly =) Have a nice day!
